### ISSUE TITLE
DFT V3.2B

### ISSUE THREAD

**Issue by Chriffi** [githubdoe/DFTFringe#1]
Hey thats a fedback th the new V3.2B.
I hope this is the right place for feedback.
I tried to analyse an Igram in Autokollimation. Works well but when i tryed to edit the colors, the contour tab is greyed out. No changes can be made.

Second: In V3.2 When i try to change the max/min scale to min=0 and max= 0,5 waves the 2D plot works well but the 3D plot became black in some low parts of the Plot.

thanks cs

**Comment by atsju** [comment]
@gr5  @githubdoe Maybe this issue can be closed now.
This one is certainly fixed or outdated.

**Comment by githubdoe** [comment]
Current version of DFTFringe does not use the 3D plot controls or display and has different code.  This 3D plot issue no longer applies.
