### ISSUE TITLE
another out-of-matrix crash

### ISSUE THREAD

**Issue by gr5** [githubdoe/DFTFringe#144]
**To Reproduce**

This is extremely repeatable.

open DFTF, in mirror config click annular box and set to 50%.  Nothing else matters in mirror config.
simulate igram, settings don't matter but I did 600 pixels, click ok
in igram window click "done" (no need to set inner outline), click "compute surface"

now go back to "mirror config".  Uncheck annulus, click ok.  Wait a few seconds for it to process.  now go to mirror dialog, check annulus and click ok. 

You can see the progress bar slide across and it crashes part way through - here's the line of code where it crashes in ZernFitWavefront()

For my 600X600 igram and DFT, it crashes when i reaches 211288.  m_rhoTheta.n_cols is unfortunately larger at 277976.
![Capture](https://github.com/githubdoe/DFTFringe/assets/5414808/4437404d-7f8c-41ac-bf5b-49179f4d3d98)

**Comment by gr5** [comment]
Dale seemed to find the last issue pretty quickly.  I'm hoping this one is easy as well.  It seems some things are cached and not properly recalculated?  Do I have that right?  Is it possible to encapsulate the problem in a class where the class itself keeps track of if things need to be recalculated?  I'm not sure what the issue is.

**Comment by githubdoe** [comment]
I tired to make initgrid smart and not always run if it did not need to be.  It is still to stupid.  We keep finding cases where it should run but does not think it does.  I'm inclined to just remove that if need be code.  However then we may discover why I made it in the first place.  

I don't have time at the moment.  But you can play with it if you do.  You will see an if with a lot of conditions.  That is the one.  In zernikeprocess::initgrid().   There is also a variable that others can set called needsinit.  That is how I fixed the last one when the caller wants to force an init.

**Comment by gr5** [comment]
Ah.  I'll look at this...

**Comment by gr5** [comment]
Okay.  Fixed.  Please review PR #145
