### ISSUE TITLE
[bug] autoload outline won't load exclusion region

### ISSUE THREAD

**Issue by atsju** [githubdoe/DFTFringe#19]
Version 6.2

From my understanding, today the .oln file contains the outline, regions and the DFT limit. This lets user reload same picture and modify slightly outline. When loading igram, the outline is loaded automagically.

Problem: on my computer, when loading an igram, the corresponding outline and DFT are loaded, but regions are not.
When I reload the outline file manually, everything is updated correctly

**Comment by gr5** [comment]
Looking at this now.

**Comment by githubdoe** [comment]
I think that is because the regions were not saved properly into the QSettings when they are modified at crop time.
I think I fixed that IIRC recently in the last few weeks if my changes got pushed.

**Comment by gr5** [comment]
I thought *I* fixed this a few weeks ago, lol.

I wonder if we both made changes that were incompatible and it's broken again.  Anyway I will look at this next.  It's definitely not 100% working as expected.

**Comment by githubdoe** [comment]
All I did if it made it into the archive was to add saving them to the QSettings when deleted or crop was invoked. IIRC  however that was around the time my disk drive crashed.  Then what I remember is trying to recreate the fix and then pushing it.  So it might be with my last push which also delt with the config edge mask.
