### ISSUE TITLE
Check and potentially remove Armadillo usage

### ISSUE THREAD

**Issue by atsju** [githubdoe/DFTFringe#29]
https://github.com/githubdoe/DFTFringe/pull/18#pullrequestreview-1453584023

maybe we can remove it if unused

**Comment by githubdoe** [comment]
It is used by zernike process for the code that Mike Peck gave me.   His code is used or is planned to be used to compute zernike values for annular interferograms values.

**Comment by gr5** [comment]
okay.  Sounds good.  closing this issue.

**Comment by atsju** [comment]
Just to mention the issue has already been opened and closed. I think it must be linked with #119 

If we indeed update Mikes code then we need to keep Armadillo build. Else, we might remove the DLL and keep only header files. To be double checked

**Comment by githubdoe** [comment]
I will try without the .dll just to see.

**Comment by githubdoe** [comment]
It looks like I too do not have to use the armadillo.dll file and in fact do not have it in the release build. 
Code compiles with the latest downloaded armadillo.  Code crashes and will not start but that will be found.
