### ISSUE TITLE
Each recalculate grows all the regions

### ISSUE THREAD

**Issue by gr5** [githubdoe/DFTFringe#50]
**Describe the bug**
regions grow on every recalculation.  This is bad.  Someone might want to change the zernike checkboxes (e.g. remove astig) then you have to hit recalculate and now the regions grow again.

**To Reproduce**
1) analyze an igram as usual but create a small region.  
2) When final analysis is done remove gaussian filter and the region is easy to see in the wavefront.
3) Click recalculate and the region grows by 2 pixels or 10% (whichever is smaller).  Sometimes you also get unwrap errors as the regions keep growing

**Expected behavior**
Regions shouldn't keep growing.

**Fix**
Well I'm not sure we should be growing them in the first place but one could add a flag to the region to keep track of whether it has been grown or not and never run the expansion code the second time.

**Comment by gr5** [comment]
Fixed in PR#57

**Comment by atsju** [comment]
#57
