### ISSUE TITLE
uninitialized variables

### ISSUE THREAD

**Issue by atsju** [githubdoe/DFTFringe#59]
After cleaning over 600 warnings, I finally found 2 wich could have an effect.

https://github.com/githubdoe/DFTFringe/blob/9320be9a066892862e49a2cd4edae2935cab1efb/dftarea.cpp#L1566
this variable is used uninitialized

Same for https://github.com/githubdoe/DFTFringe/blob/9320be9a066892862e49a2cd4edae2935cab1efb/igramarea.cpp#L673

@gr5 @githubdoe I let you fix them as I still do not have the level to dig into it and you will best know the effect of this potential problem.

**Comment by gr5** [comment]
These are very similar bugs.  bestSdp could be set to a very large value but I'm not sure the scale of things so it should be set to the first value.  For example you could have a:
bool bFirst=true;

And then the first time bestSdp is compared, just always set it to sdp and set bestIteration to 1 and clear bFirst.

The second bug is very similar, this is the 3rd time in igramarea.cpp that uses a variable by the exact same name and the code patterns should be identical in all 3 such that rmean is set to the variable resp the very first time through the loop.  Again you could use bool bFirst for this.  Or you could check if rad==start.

I'd rather you fixed it and I approved.

I spent most of yesterday tracking down bugs in igramarea.cpp so maybe I should fix the one in there while I'm at it.  I'm dealing with issues related to storing regions, outer circle, inner circle and edge mask in registry and in OLN file and how those values change when you crop and how the priority of which ones are used on the next igram and all that.  It's confusing but I think (hope) I've found the last bug (there's not a lot of bugs and the fixes tend to be tiny changes but it's many hours trying to understand and fix them).
