### ISSUE TITLE
broken "show only average" in astig stats

### ISSUE THREAD

**Issue by atsju** [githubdoe/DFTFringe#85]
**Describe the bug**
"show only average" does still show all points.
![image](https://github.com/githubdoe/DFTFringe/assets/4628382/3ab2cffe-5788-44f8-b5a8-8acbf9eae46b)
probably introduced by my change in #75 :( 

**Desktop (please complete the following information):**
 - OS: Win
 - DFTFringe version: v7.0.0
 - Build: official

**Comment by githubdoe** [comment]
Yes I think it is.  For some reason I don't think I'm getting all emails on the issues.  For instance I did not get my posting of this issue but maybe github is smart enough to not email the originator.  So it is possible I just lost the first posting of this issue.

**Comment by gr5** [comment]
I wasn't getting notices of new pull requests for the last year; so a week ago I finally googled how to get all notifications and I just did that.  Some setting on github.
